---
title: C6312
ms.date: 11/04/2016
ms.prod: visual-studio-dev15
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: 74ea9c013996ba29a3e29b724c41c3cac1e12127
ms.sourcegitcommit: e13e61ddea6032a8282abe16131d9e136a927984
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 04/26/2018
ms.locfileid: "31897056"
---
# <a name="c6312"></a>C6312
upozornění C6312: možné nekonečná smyčka: použití konstantní exception_continue_execution – ve výrazu filtru výjimek zkuste to – s výjimkou

 Toto upozornění se označuje použití konstanty `EXCEPTION_CONTINUE_EXECUTION` (nebo jiné konstanta, která vyhodnotí na hodnotu -1) ve výrazu filtru obslužné rutiny strukturovaného výjimek. Konstantní hodnota `EXCEPTION_CONTINUE_EXECUTION` může vést k nekonečné smyčce. Například pokud hardwarem došlo k výjimce, bude restartován pokyn, který způsobil výjimku. Pokud je stále chybný adresu, která způsobila výjimku, další výjimku dojde a zpracovávat stejným způsobem. To způsobí, že nekonečné smyčce.

 Explicitní volání `RaiseException` není přímo příčina nekonečnou smyčku, ale bude pokračovat v provádění kódu v chráněném bloku. To může neočekávaná a může vést k nekonečné smyčce, pokud `RaiseException` byl použit k vyhodnocení neplatný ukazatel.

 Obvykle `EXCEPTION_CONTINUE_EXECUTION` má být vrácen pouze ve funkci s názvem ve výrazu filtru, který má možnost opravit buď má ukazatel, který způsobil výjimku nebo základní paměti.

## <a name="example"></a>Příklad
 Následující kód vytvoří toto upozornění:

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
   *ptr = '\0';
  }
  __except (EXCEPTION_CONTINUE_EXECUTION)
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler
    //  block of the structured exception handler is not executed.
  {
    puts("This block is never executed");
  }
}
```

 Chcete-li toto upozornění, použijte následující kód:

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
    *ptr = '\0';
  }
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
  {
    puts("Error Occurred");
  }
}
```