---
title: C6318
ms.date: 11/04/2016
ms.prod: visual-studio-dev15
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C6318
helpviewer_keywords:
- C6318
ms.assetid: 3284a83e-bb8e-461c-adcc-cfc66ceea05e
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: 73dae483e22b486b9204df97958966e83da66527
ms.sourcegitcommit: e13e61ddea6032a8282abe16131d9e136a927984
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 04/26/2018
ms.locfileid: "31895065"
---
# <a name="c6318"></a>C6318
upozornění C6318: chybně definované __try /\__except: použití konstantní exception_continue_search – nebo jiné konstanta, která vyhodnotí nule ve výrazu filtru výjimek. Kód v bloku obslužná rutina výjimky není spuštěn.

 Toto upozornění znamená, že pokud dojde k výjimce v chráněném bloku této rutiny strukturovaného výjimek, výjimka nebudou zpracována, protože konstanta `EXCECPTION_CONTINUE_SEARCH` se používá ve výrazu filtru výjimek.

 Tento kód je ekvivalentní chráněné bloku bez bloku obslužná rutina výjimky, protože není proveden bloku obslužné rutiny.

## <a name="example"></a>Příklad
 Následující kód vytvoří toto upozornění:

```
#include <excpt.h>
#include <stdio.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except (EXCEPTION_CONTINUE_SEARCH) // warning 6318
  {
    puts("Exception Occurred");
  }
}
```

 Chcete-li toto upozornění, použijte následující kód:

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except( (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION) ?
                EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )
  {
    puts("Access violation");
  }
}
```

## <a name="see-also"></a>Viz také
 [try-except – příkaz](/cpp/cpp/try-except-statement)